# if a push is made into any branch
# this will build node_modules and typescript code
name: Build
on: [push, pull_request]
jobs:
  # make sure we can build
  build:
    name: Build code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make run
