# on push to release-promotion this will build the production code and push to release
# also run a test release every sunday at 5pm gmt
name: Release Build
on:
  schedule:
    - cron: 0 17 * * *
  push:
    branches:
      - release-promotion
jobs:
  # if push to master then build for release, and push to releases/v1 branch
  release_build:
    name: Build and push to release branch
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TRILOM_BOT_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          # TODO: CHANGE TO master BRANCH
          branch: develop
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
          dry_run: true
      - name: Test Outputs
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
      - run: make run COMMAND=release RELEASE=TRUE
        # TODO: CHANGE TO master BRANCH
        if: endsWith( github.ref, 'develop') && steps.semantic.outputs.new_release_published == 'true'
      - name: Push release files
        if: endsWith( github.ref, 'develop') && steps.semantic.outputs.new_release_published == 'true'
        # TODO: CHANGE TO releases/v1 BRANCH 
        run: |
          git config --local user.email "trilom-bot@trailmix.me"
          git config --local user.name "trilom-bot"
          git add --all
          git commit -m "Add release changes ⚙️" -a
          git push -f https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/test/v${{steps.semantic.outputs.new_release_major_version}}