# if a pr is made into master and any further pushes(syncronize)
# this will run jest
name: Test
on: 
  pull_request:
    branches:
      - '**'
jobs:
  # test with jest
  test:
    name: jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make run
      - run: make run COMMAND=test
